### ISSUE TITLE
Storm Tempests issue

### ISSUE THREAD

**Issue by darhanger** [CuteOne/BadRotations#6]
Have error with Storm Tempests. When I am wearing Storm Tempests, rotation just skip stormstrike.

**Comment by CuteOne** [comment]
Strange as there is specific code that handles this...and regardless the normal code should still work as there is nothing preventing it from being used.

**Comment by darhanger** [comment]
Maybe its some like mod of stortmstrike? and after equiping this belt its mod and change this spell.

**Comment by CuteOne** [comment]
Well can you verify the Tempest Debuff Id and Stormstrike Id?

**Comment by darhanger** [comment]
Don't know what you mean 
http://www.wowhead.com/spell=214260/storm-tempests#used-by-item
http://www.wowhead.com/spell=214265/storm-tempests 

Belt just apling aura

**Comment by darhanger** [comment]
http://sendvid.com/mq2gdmy3

**Comment by Vilt-Coding** [comment]
Can you check what the Stormstrike Spell ID is with, and without the legendary equipped?

**Comment by Vilt-Coding** [comment]
Also, can you make a screenshot or video with Rotation Log and Display Failcasts enabled?

**Comment by CuteOne** [comment]
There was an issue with debuff registration latest update should fix this and should resolve this as well, please let me know.

**Comment by darhanger** [comment]
Not fixed:

Stormstrike ID with belt and without same: 17364
Video with rotation ↑

**Comment by CuteOne** [comment]
Latest commit fixes this, you can thank Doomah in Discord for it.

**Comment by darhanger** [comment]
Tnx, all work
